### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by chriskamphuis** [osirrc2019/olddog-docker#1]
Example:

https://github.com/osirrc/anserini-docker

**Comment by lintool** [comment]
Comments:
- AP 0.1771 seems a bit low... have you debugged this? also lower than the SIGIR 2014 short: AP 0.225
- Is the name of the system Olddog or OldDog? We've been using "OldDog" but let's be consistent? (but repo convention is all lowercase, `olddog`)

**Comment by chriskamphuis** [comment]
The SIGIR 2014 short is on different collection, although I agree the effectiveness scores are to low. Have to look at that. 
I agree to be consistent on the naming. Lets go for OldDog.

**Comment by Chriskamphuis** [comment]
> The SIGIR 2014 short is on different collection, although I agree the effectiveness scores are to low. Have to look at that.
> I agree to be consistent on the naming. Lets go for OldDog.

**Comment by lintool** [comment]
Oh duh. Re: effectiveness.

Still, effectiveness is quite a bit lower than I expect: https://github.com/castorini/anserini/blob/master/docs/regressions-robust04.md

Is it due to conjunctive processing?

**Comment by chriskamphuis** [comment]
Maybe, some queries only return one document for example, but in order to be sure I have to test it without the conjuctive processing.

**Comment by chriskamphuis** [comment]
Without conjunctive processing I find the following effectiveness scores:
```
map                   	all	0.2434
P_30                  	all	0.2985
```

**Comment by lintool** [comment]
Yes, much more reasonable!

**Comment by arjenpdevries** [comment]
Surprisingly large drop due to conjunctive!

**Comment by lintool** [comment]
Add these results to README?
