### ISSUE TITLE
One topic is is not being scored

### ISSUE THREAD

**Issue by chriskamphuis** [osirrc2019/olddog-docker#8]
Only 249 topics are now scored, probably a bug in the topicreader.

**Comment by chriskamphuis** [comment]
All topics are being scored upon expection of the run file; probably one topic returns no relevant documents.

**Comment by arjenpdevries** [comment]
I do not like "probably" :-)

**Comment by arjenpdevries** [comment]
The following should of course have been SQL queries...

    cut -d' ' -f1 out/robust04 | sort -n | uniq > r1.txt
    trec_eval -cq qrels/qrels.robust04.txt out/robust04 | grep num_rel_ret | grep -v all | cut -f2 | sort -n > r2.txt
    diff r1.txt r2.txt

Topic **672** is missing from the `trec_eval` output (the runfile has however 16461 entries).

I found that the `qrels.robust04.txt` has no entries for that topic:

    671 0 LA123190-0100 1
    673 0 FBIS3-12763 0

So remaining question is whether there should not be any, or there was a mistake in creating the file in the `jig`.

**Comment by arjenpdevries** [comment]
Ok, see the [overview paper](https://trec.nist.gov/pubs/trec13/papers/ROBUST.OVERVIEW.pdf):
_As noted above, topic 672 had no documents judged._
